### PR TITLE
Fix issue with data sets in series exceeding the maximum of 1000 points

### PR DESCRIPTION
**Pull request by gjong**
If you add series with data sets that exceed 1000 points HighCharts will fail with the current setup. I've added some code to return lists of lists of points, as suggested by HighCharts.

### CODE REVIEW

**Comment by a5hik** [comment]
@gjong I had done a code review, please see the comments.

**Comment by gjong** [comment]
With regards to the 800 / 900 i've been playing to see what the maximum or optimal points are before Highchart becomes slower in generation. The official cap is 1000, but I've found it better to set it to 900.

**Comment by pvanassen** [comment]
To me it would make most sense to set the cap to the official limit. It is up to the user of the API if it is too slow.

**Comment by pvanassen** [comment]
@a5hik Could you recheck the code and see if it's ok?

**Comment by a5hik** [comment]
@gjong the interface needs to be more clear to the user. 

the JsonPointArray needs to be represented in a better way to depict 'lists of lists of points' in the interface. also you need to have a way to set the original JsonArray<Point> to be backward compatible.

**Pull request closed without merging**
